### ISSUE TITLE
Building fails on Ubuntu <=20.04 because of meson

### ISSUE THREAD

**Issue by paines** [actonDev/s7-imgui#9]
Ubuntu 20.04 comes with an old version of Meson. This can be remedied with installing meson from pip instead of package management e.g. via: python3 -m pip install meson. Maybe you can add this to your dev  docs.

One quesition: When starting s7-imgui a windows opens and the console is filled with a neverending of:
;attempt to apply an undefined object #<undefined> to () in #<undefined>?

Is this something to worry about ?

**Comment by actonDev** [comment]
Hey thanks for letting me know!
I'm making plenty of changes though lately (some bindings, some scheme code) and I will change the structure alltogether (I'll archive this repo and make a new one). So, I'll not look into it at the moment.

About your problem I guess it has to do with the path (cwd) where you launch the application, ie it cannot find the `main.scm` file). Let me know if you need any help figuring things out
